export {countriesInfo};
let countriesInfo = [
{
    country_id : "germany",
    country_name : "Germany",
    country_flag : "country-flags/germany-flag.png",
    country_population : "81,770,900",
    country_region : "Europe",
    country_capital : "Berlin",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Belgium", "Netherlands"],
    
},
{
    country_id : "united states of america",
    country_name : "United States of America",
    country_flag : "country-flags/usa-flag.png",
    country_population : "323,947,000",
    country_region : "America",
    country_capital : "Washington, D.C.",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "brazil",
    country_name : "Brazil",
    country_flag : "country-flags/brazil-flag.png",
    country_population : "206,135,893",
    country_region : "America",
    country_capital : "Brasilia",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "iceland",
    country_name : "Iceland",
    country_flag : "country-flags/iceland-flag.png",
    country_population : "334,300",
    country_region : "Europe",
    country_capital : "Reykjavik",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "afghanistan",
    country_name : "Afghanistan",
    country_flag : "country-flags/afghanistan-flag.png",
    country_population : "27,657,145",
    country_region : "Asia",
    country_capital : "Kabul",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "aland-island",
    country_name : "Aland Islands",
    country_flag : "country-flags/aland-islands-flag.png",
    country_population : "28,875",
    country_region : "Europe",
    country_capital : "Mariehamn",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "albania",
    country_name : "Albania",
    country_flag : "country-flags/albania-flag.png",
    country_population : "2,886,026",
    country_region : "Europe",
    country_capital : "Tirana",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "algeria",
    country_name : "Algeria",
    country_flag : "country-flags/algeria-flag.png",
    country_population : "40,400,000",
    country_region : "Africa",
    country_capital : "Algiers",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
{
    country_id : "belgium",
    country_name : "Belgium",
    country_flag : "country-flags/belgium-flag.png",
    country_population : "11,319,511",
    country_region : "Europe",
    country_capital : "Brussels",
    
    country_nativename : "België",
    country_subregion : "Western Europe",
    country_topleveldomain : ".be",
    country_currencies : "Euro",
    country_languages : "Dutch, French, German",
    country_bordercountries : ["France", "Germany", "Netherlands"],
},
]